nebitnofivem = 'Nebitno za FiveM'

AddTextEntry('FE_THDR_GTAO', Config.ImeServera)

-- ovu funkciju za ime servera mozete npr staviti u neki loop da geta id, helte, posao, itd, ovo je jednostavna verzija


 AddTextEntry('PM_SCR_VHI', 'OPCIJE')
 AddTextEntry('PM_PANE_AUD', 'Zvuk')
 AddTextEntry('PM_PANE_BRI', 'Dijalozi')
 AddTextEntry('PM_PANE_CAM', 'Kamera')
 AddTextEntry('PM_PANE_CON', 'Kontrole')
 AddTextEntry('PM_PANE_DIS', 'Ekran')
 AddTextEntry('PM_PANE_QUIT', 'Izadji sa servera')
 AddTextEntry('PM_QUIT_GAME', 'Zelite li da odmorite malo od igranja FiveM-a? Ili mozda imate druge obaveze?\nNema problema, cekamo vas na istom mestu! :D')
 AddTextEntry('PM_QUIT_K1', 'Potvrdi')
 AddTextEntry('PM_QUIT_WARN', 'Izadji sa servera')
 AddTextEntry('PM_SCR_GAL', 'GALERIJA')
 AddTextEntry('PM_SCR_GAM', 'IGRA')
 AddTextEntry('PM_SCR_MAP', 'MAPA')
 AddTextEntry('PM_SCR_SET', 'PODESAVANJA')
 AddTextEntry('PM_SCR_STA', 'STATISTIKE')
 AddTextEntry('MO_BRI', 'Osvetljenje')
 AddTextEntry('MO_BSTATS', 'Statistike')
 AddTextEntry('MO_GFX_NORM', 'Normalan')
 AddTextEntry('MO_GFX_VHIGH', 'Veoma visok')
 AddTextEntry('MO_HIGH', 'Visok')
 AddTextEntry('MO_LAN', 'Jezik ~b~(Svakako je na srpskom)')
 AddTextEntry('MO_LOW', 'Nizak')
 AddTextEntry('MO_MED', 'Srednji')
 AddTextEntry('MO_MUS', 'Jacina muzike')
 AddTextEntry('MO_OFF', 'Iskljuceno')
 AddTextEntry('MO_ON', 'Ukljuceno')
 AddTextEntry('MO_RADOFF', 'Radio iskljucen')
 AddTextEntry('MO_RDF', 'Vrati na podrazumevana podesavanja')
 AddTextEntry('MO_RETICULE_OF', 'Jednostavno')
 AddTextEntry('MO_RETICULE_ON', 'Kompleksno')
 AddTextEntry('MO_RST', 'Radio stanica')
 AddTextEntry('MO_SFX', 'Jacina efekata')
 AddTextEntry('MO_SHEAD', 'Slusalice')
 AddTextEntry('MO_VID_NAME', 'Graficka kartica')
 AddTextEntry('MO_VOICE_ALERT', 'Voice chat je mutiran dok ste na ovoj strani podesavanja.')
 AddTextEntry('MO_VOUT', 'Voice Chat')
 AddTextEntry('MO_YES', 'Da')
 AddTextEntry('MOUSE_LEFT', 'Levi klik misem')
 AddTextEntry('MOUSE_MIDDLE', 'Srednji klik misem')
 AddTextEntry('MOUSE_RIGHT', 'Desni klik misem')
 AddTextEntry('MG_KILLS', 'Ubistva mitraljezom')
 AddTextEntry('VEUI_AUD_INT_HI', 'Visok')
 AddTextEntry('VEUI_AUD_INT_LOW', 'Nizak')
 AddTextEntry('VEUI_AUD_INT_MAX', 'Maksimalno')
 AddTextEntry('VEUI_AUD_INT_MED', 'Srednje')
 AddTextEntry('VEUI_AUD_INT_MIN', 'Minimalno')
 AddTextEntry('VEUI_AUD_MIC_CIN', 'Filmski')
 AddTextEntry('UNIT_KILO', 'kilometri')
 AddTextEntry('UNIT_METERS', 'metri')
 AddTextEntry('UNIT_MILES', 'milje')
 AddTextEntry('PS_DRIVING', 'Voznja')
 AddTextEntry('PS_FLYING', 'Letenje')
 AddTextEntry('PS_LUNG', 'Kapacitet pluca')
 AddTextEntry('PS_SHOOTING', 'Pucanje')
 AddTextEntry('PS_STAMINA', 'Kondicija')
 AddTextEntry('PS_STEALTH', 'Sunjanje')
 AddTextEntry('PS_STRENGTH', 'Snaga')
 AddTextEntry('PM_WAIT', 'Molimo sacekajte')
 AddTextEntry('GFX_VIDMEM', 'Video memorija')
 AddTextEntry('GFX_WARNING_HEADER', 'Da li zelite da zadrzite nova podesavanja?')
 AddTextEntry('GFX_WARNING_BODY', 'Vracanje na stara podesavanja za ~HUD_COLOUR_YELLOW~~1~ ~s~sekundi...')
 AddTextEntry('GFX_NO_APPLY_BODY', 'Presli ste dostupnu video memoriju. Izabrana podesavanja zahtevaju vise memorije nego sto vasa graficka ima. Molimo vas da smanjite vasa podesavanja.')
 AddTextEntry('GFX_RESTART_HEADER', 'Restartuj sada?')
 AddTextEntry('GFX_SHARP', 'Ostro')
 AddTextEntry('GFX_SOFT', 'Mekano')
 AddTextEntry('GFX_SOFTER', 'Mekse')
 AddTextEntry('GFX_SOFTEST', 'Najmekse')
 AddTextEntry('IB_HIDEMENU', 'Sakrij meni')
 AddTextEntry('IB_WAYPOINT', 'Tacka putanje')
 AddTextEntry('IB_YES', 'Da')
 AddTextEntry('IB_ZOOM', 'Uvecanje')
 AddTextEntry('IB_NO', 'Ne')
 AddTextEntry('IB_EXIT', 'Izadji')
 AddTextEntry('IB_LEGEND', 'Izaberi blip')
 AddTextEntry('IB_MAPMOVE', 'Pomeri mapu')
 AddTextEntry('IB_THUMBNAIL', 'Nazad')
 AddTextEntry('WARNING_EXIT_WINDOWS', 'Izadji sa servera')
 AddTextEntry('EXIT_SURE', 'Da li stvarno zelite da izadjete sa servera?\nSav dosadasnji napredak bi trebalo biti sacuvan, osim ako nije drugacije najavljeno ranije!')
 AddTextEntry('INPUTGROUP_LOOK', 'Gledanje')
 AddTextEntry('INPUTGROUP_MOVE', 'Pomeranje')
 AddTextEntry('INPUT_ACCURATE_AIM', 'Precizno nisanjenje')
 AddTextEntry('INPUT_AIM', 'Nisani')
 AddTextEntry('INPUT_CHANGE_CAMERA_DISPLAYONLY', 'Promeni kameru')
 AddTextEntry('INPUT_COVER', 'Uzmi zaklon')
 AddTextEntry('INPUT_CLIMB_DISPLAYONLY', 'Penji se')
 AddTextEntry('INPUT_ENTER', 'Udji u vozilo')
 AddTextEntry('INPUT_FRONTEND_ACCEPT', 'Prihvati')
 AddTextEntry('INPUT_JUMP', 'Skoci')
 AddTextEntry('INPUT_FRONTEND_CANCEL', 'Otkazi')
 AddTextEntry('INPUT_DETONATE', 'Detoniraj C4')
 AddTextEntry('INPUT_SPRINT', 'Trci')
 AddTextEntry('0xFB0E70C2', 'VSync')
 AddTextEntry('VEUI_QUAL_HIGH', 'Visok')
 AddTextEntry('MO_CS_HIGH', 'Visok')
 AddTextEntry('VEUI_TIME_ADJ', 'Promeni')
 AddTextEntry('IB_ADJUST', 'Promeni')
 AddTextEntry('VEUI_ED_MK_MIC', 'Tip mikrofona')
 AddTextEntry('VOX_FEEDBACK', 'Jacina glasa')
 AddTextEntry('INPUT_SELECT_CHARACTER_FRANKLIN', nebitnofivem)
 AddTextEntry('INPUT_SELECT_CHARACTER_MICHAEL', nebitnofivem)
 AddTextEntry('INPUT_SELECT_CHARACTER_MULTIPLAYER', nebitnofivem)
 AddTextEntry('INPUT_SELECT_CHARACTER_TREVOR', nebitnofivem)
 AddTextEntry('INPUT_INTERACTION_MENU', nebitnofivem)
 AddTextEntry('INPUT_CHARACTER_WHEEL', nebitnofivem)
 AddTextEntry('INPUT_CONTEXT', 'Interakcija')
 AddTextEntry('INPUT_FRONTEND_PAUSE', 'Pauza')
 AddTextEntry('INPUT_RELOAD', 'Repertiraj')
 AddTextEntry('INPUT_HUD_SPECIAL', 'Informacije o levelu')
 AddTextEntry('INPUT_NEXT_CAMERA', 'Promena kamere')
 AddTextEntry('INPUT_SPECIAL_ABILITY_PC', nebitnofivem)
 AddTextEntry('LANG_E', 'Srpski')
 AddTextEntry('IB_BACK', 'Nazad')
 AddTextEntry('IB_CANCEL', 'Otkazi')
 AddTextEntry('IB_CONFIRM', 'Potvrdi')
 AddTextEntry('IB_DELETE', 'Obrisi')
 AddTextEntry('IB_EDIT', 'Izmeni')
 AddTextEntry('IB_SELECT', 'Izaberi')
 AddTextEntry('HUD_INPUT1C', 'Pregledaj')
 AddTextEntry('IB_UPDATE_SOCIAL_CLUB', 'Sakrij kursor')
 
 AddTextEntryByHash(0xFBB6E685, "Napredna podesavanja grafike")
 AddTextEntryByHash(0xD3A0C438, "Grafika")
 AddTextEntryByHash(0x92320117, "Dzojstik")
 AddTextEntryByHash(0x0A0C22D4, "Tastatura i mis")
 AddTextEntryByHash(0x82FBED04, "Kontrole")
 AddTextEntryByHash(0x8A29ABD8, "Nazad")
 AddTextEntryByHash(0x9D36D7F3, "Izaberi")
 AddTextEntryByHash(0xA68B1B92, "Pregledaj")
 AddTextEntryByHash(0x67117E6F, "Ignorisi preporucene limite")
 AddTextEntryByHash(0x87D30231, "Verzija DirectX-a")
 AddTextEntryByHash(0xC4FD3301, "Pauziraj igru kada FiveM nije aktivan prozor")
 AddTextEntryByHash(0x78F76ACC, "Kvalitet tekstura")
 AddTextEntryByHash(0x5CD4E15C, "Kvalitet trave")
 AddTextEntryByHash(0x74F73ED3, "Kvalitet senki")
 AddTextEntryByHash(0xC43D3B9F, "Kvalitet vode")
 AddTextEntryByHash(0xCD676AF6, "Kvalitet odsjaja")
 AddTextEntryByHash(0x5617744E, "Hvala sto ste igrali na nasem serveru, administracija vam zeli prijatan dan!\nIzlazite sa servera, molimo sacekajte...")
 AddTextEntryByHash(0x73C258A0, "Mekoca senki")
 AddTextEntryByHash(0xB63ADD91, "~r~Menjanje ovih podesavanja moze znacajno lose uticati na FPS!")
 AddTextEntryByHash(0x15C37CCF, "Tip ekrana")
 AddTextEntryByHash(0x7AD96F62, "Kao prozor (Windowed)")
 AddTextEntryByHash(0xA75F44D9, "Mesavina Fullscreena i prozora (Windowed Borderless)")
 AddTextEntryByHash(0xB287B54A, "Rezolucija")
 AddTextEntryByHash(0x6BF143E4, "Brzina osvezavanja")
 AddTextEntryByHash(0xB2C51344, "Odnos stranica")
 AddTextEntryByHash(0x62EEC30D, "Automatski")
 AddTextEntryByHash(0xE0FD16F8, "Duge senke")
 AddTextEntryByHash(0xC51AAD71, "Senke u viskoj rezoluciji")
 AddTextEntryByHash(0xA334EBB9, "Produzena distanca senki")
 AddTextEntryByHash(0x2491D810, "Visoki detalji kopna tokom letenja")
 AddTextEntryByHash(0xF84B169F, "Nivo detalja i distanca ucitavanja detalja")
 AddTextEntryByHash(0x5CEE5914, "Produzeni nivo detalja i distanca ucitavanja detalja")
 AddTextEntryByHash(0x2636DDA8, "Menjanje podesavanja dok ste na serveru moze izazvati probleme sa konekcijom tokom trenutne sesije. ~b~(Uglavnom nece)~w~. \nDa li zelite da nastavite?")
 AddTextEntryByHash(0x95A3910E, "Primeni promene")
 AddTextEntryByHash(0x4961F2F7, "Promeni")
 AddTextEntryByHash(0xFB9CF659, "Pola")
 AddTextEntryByHash(0x9312C4B0, "Promenite kontrole misa i tastature za GTA i komande na nasem serveru kako god vama odgovara. Ne mozete menjati bindove na dzojsticima.\nA i budimo realni, ko jos igra FiveM na dzojsticima? :D\n\nPritisnite ~INPUT_FRONTEND_ACCEPT~ da promenite bind kada ga unesete.")
 AddTextEntryByHash(0x242FF5F0, "Ukljucivanje voice chata")
 AddTextEntryByHash(0x666AB89C, "Slusanje voice chata")
 AddTextEntryByHash(0x3A967027, "Slusalice/Zvucnik/Sta vec koristite za slusanje")
 AddTextEntryByHash(0x5B1E238A, "Jacina muzike dok neko drugi prica")
 AddTextEntryByHash(0x70A49757, "Jacina efekata dok neko drugi prica")
 AddTextEntryByHash(0xEA2A4F25, "Mod Voice Chat-a ( ~INPUT_PUSH_TO_TALK:0~ )")
 AddTextEntryByHash(0xEBF9F181, "Mod Voice Chat-a")
 AddTextEntryByHash(0xF67B0E1A, "Jacina Voice Chat-a")
 AddTextEntryByHash(0x303F7BDD, "Pricanje u voice chatu")
 AddTextEntryByHash(0x0BE851D4, "Osetljivost mikrofona")
 AddTextEntryByHash(0x70F9FCDD, "Jacina mikrofona")
 AddTextEntryByHash(0xEBFAE560, "Ukljucivanje mikrofona")
 AddTextEntryByHash(0x9E35D93A, "Mikrofon")
 AddTextEntryByHash(0x582F36B8, "Zadrzite za pricanje")
 AddTextEntryByHash(0x8828B37A, 'Automatski aktivirano ~r~(Ne preporucuje se)')
 AddTextEntryByHash(0x601593A7, "Akcija")
 AddTextEntryByHash(0xBA54784C, "Glavno")
 AddTextEntryByHash(0x05F376C3, "Sporedno ~r~(Ne radi FiveM)")
 AddTextEntryByHash(0x59138C92, "Milje i ostale americke gluposti")
 AddTextEntryByHash(0xF7E43E18, "Metri")
 AddTextEntryByHash(0xD1C027C3, "Sistem mera")
 AddTextEntryByHash(0xF1AB6BFB, "Nazad")
 AddTextEntryByHash(0x6DF4F7FD, 'Sakrij kursor')
